# Generated by Django 3.0.8 on 2020-07-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('School', 'School'), ('Accountant', 'Accountant'), ('Teacher', 'Teacher'), ('Reception', 'Reception'), ('Student', 'Student')], default='Student', max_length=200),
        ),
    ]
