# Generated by Django 3.0.8 on 2020-07-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20200712_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
