# Generated by Django 3.0.8 on 2020-07-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_auto_20200712_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='uid',
            new_name='id',
        ),
    ]
