# Generated by Django 3.0.8 on 2020-07-12 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_auto_20200712_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2970edf3-c43f-11ea-98df-402343e1102e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
