# Generated by Django 3.0.8 on 2020-07-12 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_auto_20200712_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.UUIDField(default=uuid.UUID('11d24f09-c440-11ea-9e08-402343e1102e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
