# Generated by Django 3.0.8 on 2020-07-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_auto_20200712_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.CharField(default='5403792c-c440-11ea-8613-402343e1102e', editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
