# Generated by Django 3.0.8 on 2020-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_auto_20200712_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.CharField(default='4b45bf2e-c441-11ea-b802-402343e1102e', max_length=200, primary_key=True, serialize=False),
        ),
    ]
