# Generated by Django 3.0.8 on 2020-07-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_auto_20200712_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.CharField(default='9bffbc02-c445-11ea-a1d7-402343e1102e', editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
