# Generated by Django 3.0.8 on 2020-07-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_auto_20200712_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.CharField(default='2cf0ee98c44a11ea9fe1402343e1102e', editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
