# Generated by Django 3.0.8 on 2020-07-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_auto_20200717_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorMessage',
        ),
        migrations.DeleteModel(
            name='LoginPayload',
        ),
        migrations.DeleteModel(
            name='LoginResponse',
        ),
    ]
