# Generated by Django 3.0.8 on 2020-07-21 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_auto_20200717_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.UUIDField()),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=100)),
                ('schoolid', models.CharField(max_length=100)),
                ('classid', models.IntegerField(max_length=100)),
                ('attendancedate', models.DateTimeField(verbose_name='mm-dd-yyyy')),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schoolid', models.CharField(max_length=100)),
                ('classname', models.IntegerField(max_length=2)),
                ('section', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.UUIDField()),
                ('schoolid', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('classid', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(verbose_name='mm-dd-yyyy')),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.IntegerField(max_length=6)),
                ('dateOfJoining', models.DateTimeField(verbose_name='mm-dd-yyyy')),
                ('salary', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeeDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=100)),
                ('schoolid', models.CharField(max_length=100)),
                ('classid', models.CharField(max_length=100)),
                ('feestructureid', models.IntegerField(max_length=100)),
                ('depositdate', models.DateTimeField(verbose_name='mm-dd-yyyy')),
                ('depositamount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classid', models.CharField(max_length=100)),
                ('schoolid', models.CharField(max_length=100)),
                ('feename', models.CharField(max_length=100)),
                ('cycle', models.IntegerField(max_length=100)),
                ('amount', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classid', models.CharField(max_length=100)),
                ('teacherid', models.CharField(max_length=100)),
                ('schoolid', models.CharField(max_length=100)),
                ('homeworkdate', models.DateTimeField(verbose_name='mm-dd-yyyy')),
                ('homework', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.UUIDField()),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.UUIDField()),
                ('schoolid', models.CharField(max_length=200)),
                ('classid', models.CharField(max_length=200)),
                ('dob', models.DateTimeField(verbose_name='mm-dd-yyyy')),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('mobileno1', models.CharField(max_length=10)),
                ('mobileno2', models.CharField(max_length=10)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.IntegerField(max_length=6)),
                ('admissiondate', models.DateTimeField(verbose_name='mm-dd-yyyy')),
                ('srno', models.IntegerField(max_length=200)),
                ('promotedclassid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransferCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=100)),
                ('schoolid', models.CharField(max_length=200)),
                ('requestedby', models.CharField(max_length=100)),
                ('approvedby', models.CharField(max_length=100)),
                ('requestdate', models.DateTimeField(verbose_name='mm-dd-yyyy')),
                ('approvedate', models.DateTimeField(verbose_name='mm-dd-yyyy')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
