# Generated by Django 3.0.8 on 2020-07-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_admin_attendance_class_employee_feedeposit_feestructure_homework_school_student_transfercertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='cycle',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='srno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
