# Generated by Django 3.0.8 on 2020-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_auto_20200721_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='classname',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='feedeposit',
            name='feestructureid',
            field=models.CharField(max_length=100),
        ),
    ]
