# Generated by Django 3.0.8 on 2020-07-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_auto_20200722_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
