# Generated by Django 3.0.8 on 2020-07-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0023_auto_20200722_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='zip',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='school',
            name='zip',
            field=models.CharField(max_length=7),
        ),
    ]
