# Generated by Django 3.0.8 on 2020-07-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0024_auto_20200724_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classname',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
