# Generated by Django 3.0.8 on 2020-07-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_auto_20200730_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendancedate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dateOfJoining',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feedeposit',
            name='depositdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homeworkdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='admissiondate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='classid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='approvedate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='requestdate',
            field=models.DateTimeField(),
        ),
    ]
