# Generated by Django 3.0.8 on 2020-07-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_auto_20200731_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendancedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dateOfJoining',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feedeposit',
            name='depositdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homeworkdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='admissiondate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='approvedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='requestdate',
            field=models.DateField(),
        ),
    ]
