# Generated by Django 3.0.8 on 2020-07-31 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_auto_20200731_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classid', models.CharField(max_length=100)),
                ('subjectname', models.CharField(max_length=100)),
            ],
        ),
    ]
