# Generated by Django 3.0.8 on 2020-07-31 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPortal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjectid', models.CharField(max_length=100)),
                ('chaptername', models.CharField(max_length=100)),
                ('videolink', models.CharField(max_length=500)),
            ],
        ),
    ]
