# Generated by Django 3.0.8 on 2020-08-01 19:08

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_auto_20200801_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schoolid', models.CharField(max_length=100)),
                ('classid', models.CharField(max_length=100)),
                ('subjectid', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=1)),
                ('teacherid', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 8, 2)),
        ),
    ]
