# Generated by Django 3.0.8 on 2020-08-03 18:21

import auth_app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0033_auto_20200803_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='schoolid',
        ),
        migrations.AddField(
            model_name='homework',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=auth_app.models.upload_path),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homeworkdate',
            field=models.DateField(default=datetime.date(2020, 8, 3)),
        ),
    ]
