# Generated by Django 3.0.8 on 2020-08-22 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0036_auto_20200808_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 8, 22)),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 8, 22)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homeworkdate',
            field=models.DateField(default=datetime.date(2020, 8, 22)),
        ),
        migrations.AlterField(
            model_name='login',
            name='image',
            field=models.BinaryField(),
        ),
    ]
