# Generated by Django 3.0.8 on 2020-09-09 15:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0038_auto_20200822_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('testid', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=400)),
                ('questiontype', models.CharField(max_length=12)),
                ('option1', models.CharField(blank=True, max_length=400)),
                ('option2', models.CharField(blank=True, max_length=400)),
                ('option3', models.CharField(blank=True, max_length=400)),
                ('option4', models.CharField(blank=True, max_length=400)),
                ('marks', models.CharField(max_length=400)),
                ('answer', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('testid', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questionid', models.CharField(max_length=100)),
                ('submission', models.CharField(max_length=1000)),
                ('userid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classid', models.CharField(max_length=100)),
                ('subjectid', models.CharField(max_length=100)),
                ('testname', models.CharField(max_length=100)),
                ('duration', models.IntegerField(max_length=1)),
                ('status', models.CharField(max_length=12)),
                ('expiredate', models.DateField(default=datetime.date(2020, 9, 9))),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 9, 9)),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 9, 9)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homeworkdate',
            field=models.DateField(default=datetime.date(2020, 9, 9)),
        ),
    ]
