# Generated by Django 3.0.8 on 2020-09-18 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0044_auto_20200916_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 9, 18)),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 9, 18)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homeworkdate',
            field=models.DateField(default=datetime.date(2020, 9, 18)),
        ),
        migrations.AlterField(
            model_name='submittedtest',
            name='testid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='expiredate',
            field=models.DateField(default=datetime.date(2020, 9, 18)),
        ),
    ]
