# Generated by Django 3.0.8 on 2020-09-19 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0045_auto_20200918_2120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmittedTest',
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 9, 19)),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 9, 19)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homeworkdate',
            field=models.DateField(default=datetime.date(2020, 9, 19)),
        ),
        migrations.AlterField(
            model_name='result',
            name='testid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='expiredate',
            field=models.DateField(default=datetime.date(2020, 9, 19)),
        ),
    ]
