# Generated by Django 3.0.8 on 2020-09-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0046_auto_20200919_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.CharField(default='Processing', max_length=20),
        ),
    ]
