# Generated by Django 3.0.8 on 2020-09-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0048_auto_20200919_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
