# Generated by Django 3.0.8 on 2020-09-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0050_auto_20200919_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='testid',
            field=models.CharField(max_length=100),
        ),
    ]
