# Generated by Django 3.0.8 on 2020-09-20 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0052_auto_20200919_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 9, 20)),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 9, 20)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homeworkdate',
            field=models.DateField(default=datetime.date(2020, 9, 20)),
        ),
        migrations.AlterField(
            model_name='test',
            name='expiredate',
            field=models.DateField(default=datetime.date(2020, 9, 20)),
        ),
    ]
