# Generated by Django 3.0.8 on 2020-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0054_auto_20200922_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='userid',
            field=models.CharField(max_length=200),
        ),
    ]
