# Generated by Django 3.0.8 on 2020-09-26 06:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0056_auto_20200926_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='roomid',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
