# Generated by Django 3.0.8 on 2020-09-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0057_auto_20200926_1152'),
        ('auth_app', '0039_auto_20200912_2248'),
    ]

    operations = [
    ]
