# Generated by Django 3.0.8 on 2020-09-28 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0058_merge_20200928_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 9, 28)),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendancedate',
            field=models.DateField(default=datetime.date(2020, 9, 28)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homeworkdate',
            field=models.DateField(default=datetime.date(2020, 9, 28)),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='roomid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='expiredate',
            field=models.DateField(default=datetime.date(2020, 9, 28)),
        ),
    ]
